const KEY='intent-workbench-v1';
const sample={
  intents:[
    {id:1,title:'Improve onboarding',outcome:'Help a new engineer understand the project and create a valid intent without outside instruction.',inputs:'Project intent; context files; sample project',outputs:'Guided start screen and example intent',constraints:'No login; no backend; no hidden prerequisites',success:'A new user can create a ready intent in under 5 minutes',stop:'The flow passes the readiness check',stake:'medium'},
    {id:2,title:'Evidence-first review',outcome:'Make review findings easy to verify rather than merely persuasive.',inputs:'Active intent; changed files; review context',outputs:'Findings with evidence labels and gap statement',constraints:'Review only; do not modify files',success:'Every finding has evidence and every criterion has a status',stop:'All criteria marked met, unmet, or untested',stake:'high'}
  ],
  evidence:[
    {type:'observed',text:'The project runs from a static HTTP server with no build step.',source:'reference-final/'},
    {type:'inferred',text:'Local-first storage lowers setup friction for a 28-day learning project.',source:'architecture decision'},
    {type:'assumed',text:'A team would want shared synchronization after repeated use.',source:'unverified future need'}
  ],
  capabilities:[
    {name:'Intent Check',level:'skill',owner:'Project team',version:'1.0',uses:8},
    {name:'Evidence-First Review',level:'skill',owner:'Project team',version:'1.0',uses:4},
    {name:'Release Readiness',level:'workflow',owner:'Project team',version:'0.3',uses:2}
  ],
  completedDays:[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]
};
const navItems=[['dashboard','⌂','Dashboard'],['intents','◎','Intent Builder'],['context','▦','Context'],['evidence','◫','Evidence & Review'],['capabilities','◇','Capabilities'],['architecture','⌘','Architecture'],['progress','✓','28-Day Progress']];
const contextDocs=[['Architecture','Local-first browser app; add infrastructure only when evidence requires it.'],['Business Rules','Intent, success criteria, constraints, evidence labels, and promotion rules.'],['Security','No browser secrets; untrusted content is data; human approval for high-impact work.'],['Non-Goals','Not a chat clone, autonomous-agent platform, or enterprise workflow engine.'],['Glossary','Shared definitions for intent, evidence, capability, guardrail, and stop condition.'],['UX Standard','Clear next actions, useful empty states, progressive disclosure, keyboard focus.']];
let state=load();let route='dashboard';
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(sample)}catch{return structuredClone(sample)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function score(i){let checks=[i.outcome,i.inputs,i.outputs,i.constraints,i.success,i.stop].map(v=>!!(v&&v.trim()));return Math.round(checks.filter(Boolean).length/checks.length*100)}
function badge(s){return s===100?'<span class="pill good">Ready</span>':s>=67?'<span class="pill warn">Refine</span>':'<span class="pill bad">Incomplete</span>'}
function nav(){document.getElementById('nav').innerHTML=navItems.map(([id,ico,label])=>`<button class="navbtn ${route===id?'active':''}" data-route="${id}"><span>${ico}</span><span>${label}</span></button>`).join('');document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{route=b.dataset.route;render()})}
function metric(label,value,sub=''){return `<div class="metric"><span>${label}</span><b>${value}</b><small class="muted">${sub}</small></div>`}
function dashboard(){let ready=state.intents.filter(i=>score(i)===100).length, reviews=state.evidence.filter(e=>e.type==='observed').length, done=state.completedDays.length;return `<section class="metrics">${metric('Ready intents',ready,'checkable and bounded')}${metric('Evidence records',state.evidence.length,'observed / inferred / assumed')}${metric('Capabilities',state.capabilities.length,'reusable assets')}${metric('28-day progress',`${done}/28`,Math.round(done/28*100)+'% complete')}</section><section class="layout"><div class="card"><h2>Current work</h2><p class="muted">Review intent quality before implementation.</p><div class="list">${state.intents.slice(0,3).map(i=>intentItem(i)).join('')}</div></div><div class="card cta"><span class="kicker">PROGRESSIVE INTENT</span><h2>Intent → Result → Evidence → Refined intent</h2><p>Do not add architecture because it exists. Add the next layer only when the work proves it is needed.</p><button onclick="route='progress';render()">Continue the 28-day build</button></div></section><h2 class="section-title">Trust snapshot</h2><section class="layout"><div class="card"><h3>Evidence labels</h3>${state.evidence.map(e=>`<div class="evidence-row"><b class="type-${e.type}">${e.type}</b><span>${e.text}</span><small class="muted">${e.source}</small></div>`).join('')}</div><div class="card"><h3>Release readiness</h3>${readinessChecklist(state.intents[0])}</div></section>`}
function intentItem(i){let s=score(i);return `<div class="item"><div class="item-top"><div><span class="pill">${i.stake||'medium'} stakes</span><h3>${i.title||'Untitled intent'}</h3></div>${badge(s)}</div><div class="readiness"><div class="progress" style="flex:1"><span style="width:${s}%"></span></div><span class="score">${s}%</span></div><small class="muted">${i.outcome}</small></div>`}
function intents(){return `<div class="toolbar"><p class="muted">Every intent needs an outcome, inputs, outputs, constraints, success criteria, and a stop condition.</p><button onclick="openIntent()">+ New intent</button></div><div class="intent-grid">${state.intents.map(intentItem).join('')}</div><h2 class="section-title">Intent check</h2><div class="card"><div class="checklist"><div class="check">□ Outcome is a result, not an activity</div><div class="check">□ Inputs name what may be used and what is off limits</div><div class="check">□ Output form is explicit</div><div class="check">□ Success criteria can actually be checked</div><div class="check">□ Constraints prevent scope creep</div><div class="check">□ Stop condition defines finished</div></div></div>`}
function context(){return `<p class="muted">Point rather than paste. Keep durable context in files you own.</p><div class="context-grid">${contextDocs.map(([a,b])=>`<div class="context-card"><span class="pill">context</span><h3>${a}</h3><p>${b}</p></div>`).join('')}</div>`}
function evidence(){return `<section class="layout"><div class="card"><h2>Evidence register</h2>${state.evidence.map((e,n)=>`<div class="evidence-row"><b class="type-${e.type}">${e.type}</b><span>${e.text}</span><small>${e.source}</small></div>`).join('')}</div><div class="card"><h2>Review rule</h2><p>Separate builder from reviewer. Review against the stated intent first, then defects and risk.</p><div class="checklist"><div class="check ok">✓ Require direct evidence</div><div class="check ok">✓ State what was not checked</div><div class="check ok">✓ Use deterministic checks</div><div class="check ok">✓ Human decides high-stakes outcomes</div></div></div></section><h2 class="section-title">Guardrails proportional to stakes</h2><div class="guardrails"><div class="guardrail"><span class="pill good">LOW</span><h3>Drafts & notes</h3><p>Read it. Spot-check specifics.</p></div><div class="guardrail active"><span class="pill warn">MEDIUM</span><h3>Code & internal analysis</h3><p>Tests, fresh-session AI review, and human review.</p></div><div class="guardrail"><span class="pill bad">HIGH</span><h3>Production & sensitive decisions</h3><p>All previous controls plus approval, least privilege, and audit trail.</p></div></div>`}
function capabilities(){let levels=['prompt','skill','trigger','workflow','business capability'];return `<div class="card"><h2>Capability ladder</h2><div class="flow">${levels.map((x,i)=>`<div>${x}</div>${i<levels.length-1?'<span>→</span>':''}`).join('')}</div></div><h2 class="section-title">Reusable library</h2><div class="cap-grid">${state.capabilities.map(c=>`<div class="cap-card"><span class="pill">${c.level}</span><h3>${c.name}</h3><p><b>Owner:</b> ${c.owner}<br><b>Version:</b> ${c.version}<br><b>Recorded uses:</b> ${c.uses}</p></div>`).join('')}</div>`}
function architecture(){return `<div class="card"><span class="kicker">OPERATING MODEL</span><h2>Structure the boundary, not the reasoning.</h2><p class="muted">The repository carries intent, context, evidence, and reusable procedures. The model can reason inside that boundary.</p><div class="flow"><div>Intent</div><span>→</span><div>Context</div><span>→</span><div>Build</div><span>→</span><div>Evidence</div><span>→</span><div>Review</div><span>→</span><div>Capability</div></div></div><section class="layout"><div class="card"><h3>What stays human</h3><p>Judgment, accountability, risk acceptance, business tradeoffs, and high-stakes approval.</p></div><div class="card"><h3>What AI accelerates</h3><p>Reading, searching, comparing, drafting, checking consistency, generating options, and challenging assumptions.</p></div></section>`}
function progress(){let titles=['Baseline outcome','Prompt → intent','Checkable success','Constraints','Stop conditions','Intent check','First slice','Context map','Curate context','Progressive intent','Domain model','Persistence','Usability','Challenge pass','Fresh review','Evidence labels','Deterministic checks','Guardrails','Failure states','Architecture view','Intent-check skill','Review skill','Capability ladder','Metrics','Onboarding','Polish','Adversarial review','Release'];return `<div class="card"><h2>28-day build</h2><p class="muted">Click a day to mark it complete. The goal is not streaks; the goal is evidence-backed capability.</p><div class="progress"><span style="width:${Math.round(state.completedDays.length/28*100)}%"></span></div></div><h2 class="section-title">Daily progression</h2><div class="days">${titles.map((t,i)=>`<div class="day ${state.completedDays.includes(i+1)?'done':''}" data-day="${i+1}"><b>Day ${i+1}</b><p>${t}</p><small>${state.completedDays.includes(i+1)?'Completed':'Open'}</small></div>`).join('')}</div>`}
function readinessChecklist(i){let pairs=[['Outcome defined',i?.outcome],['Inputs defined',i?.inputs],['Outputs defined',i?.outputs],['Constraints explicit',i?.constraints],['Success checkable',i?.success],['Stop condition',i?.stop]];return `<div class="checklist">${pairs.map(([l,v])=>`<div class="check ${v?'ok':''}">${v?'✓':'□'} ${l}</div>`).join('')}</div>`}
function render(){nav();let label=navItems.find(x=>x[0]===route)?.[2]||'Dashboard';document.getElementById('pageTitle').textContent=label;let fn={dashboard,intents,context,evidence,capabilities,architecture,progress}[route]||dashboard;document.getElementById('app').innerHTML=fn();document.querySelectorAll('.day').forEach(d=>d.onclick=()=>{let n=+d.dataset.day;state.completedDays=state.completedDays.includes(n)?state.completedDays.filter(x=>x!==n):[...state.completedDays,n].sort((a,b)=>a-b);save();render()})}
function openIntent(){document.getElementById('modal').classList.add('open');document.getElementById('modal').setAttribute('aria-hidden','false');document.querySelector('[name=outcome]').focus()}
function closeIntent(){document.getElementById('modal').classList.remove('open');document.getElementById('modal').setAttribute('aria-hidden','true');document.getElementById('intentForm').reset()}
document.getElementById('quickAdd').onclick=openIntent;document.getElementById('closeModal').onclick=closeIntent;document.getElementById('cancelModal').onclick=closeIntent;document.getElementById('intentForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);state.intents.unshift({id:Date.now(),title:(f.get('outcome')||'New intent').slice(0,42),outcome:f.get('outcome'),inputs:f.get('inputs'),outputs:f.get('outputs'),constraints:f.get('constraints'),success:f.get('success'),stop:f.get('stop'),stake:'medium'});save();closeIntent();route='intents';render()};document.getElementById('resetBtn').onclick=()=>{if(confirm('Restore the reference sample data?')){state=structuredClone(sample);save();render()}};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeIntent()});window.openIntent=openIntent;window.render=render;window.route=route;render();
